### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by kataras** [ngrok/ngrok-go#213]
It appears that the ngrok v2.0.0 and v1.12.1 packages have a compilation bug.

```
# golang.ngrok.com/ngrok/v2/internal/tunnel/netx
C:\Users\kataras\go\pkg\mod\golang.ngrok.com\ngrok\v2@v2.0.0\internal\tunnel\netx\logged_conn.go:43:16: undefined: logext.RandId  
```

```
# golang.ngrok.com/ngrok/internal/tunnel/netx
C:\Users\kataras\go\pkg\mod\golang.ngrok.com\ngrok@v1.12.1/internal/tunnel/netx/logged_conn.go:43:16: undefined: logext.RandId
```

Cames from `logext "github.com/inconshreveable/log15/v3/ext"`

**Comment by inconshreveable** [comment]
@kataras i'm taking a look

**Comment by Alice-Lilith** [comment]
Thanks for the report. I'm trying to reproduce this but not having any luck. Here's what I've tried:

## Testing with `1.12.1`

1. `go mod init....`
2. `go get golang.ngrok.com/ngrok@v1.12.1`
3. create main.go with...

```go
package main

import (
	"context"
	"fmt"
	"log"
	"net/http"

	"golang.ngrok.com/ngrok"
	"golang.ngrok.com/ngrok/config"
)

func main() {
	if err := run(context.Background()); err != nil {
		log.Fatal(err)
	}
}

func run(ctx context.Context) error {
	ln, err := ngrok.Listen(ctx,
		config.HTTPEndpoint(),
		ngrok.WithAuthtokenFromEnv(),
	)
	if err != nil {
		return err
	}

	log.Println("Ingress established at:", ln.URL())

	return http.Serve(ln, http.HandlerFunc(handler))
}

func handler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintln(w, "Hello from ngrok-go!")
}

````

go.mod:
```
module github.com/alice-lilith/tmp

go 1.23.2

require (
	github.com/go-stack/stack v1.8.1 // indirect
	github.com/inconshreveable/log15 v3.0.0-testing.5+incompatible // indirect
	github.com/inconshreveable/log15/v3 v3.0.0-testing.5 // indirect
	github.com/jpillora/backoff v1.0.0 // indirect
	github.com/mattn/go-colorable v0.1.13 // indirect
	github.com/mattn/go-isatty v0.0.20 // indirect
	go.uber.org/multierr v1.11.0 // indirect
	golang.ngrok.com/muxado/v2 v2.0.1 // indirect
	golang.ngrok.com/ngrok v1.12.1 // indirect
	golang.org/x/net v0.30.0 // indirect
	golang.org/x/sync v0.8.0 // indirect
	golang.org/x/sys v0.26.0 // indirect
	golang.org/x/term v0.25.0 // indirect
	google.golang.org/protobuf v1.35.1 // indirect
	gopkg.in/yaml.v2 v2.4.0 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)

```

Both `go run ./main.go` and `go build` then executing the built binary work fine for me without error.



## Testing with `2.0.0`

1. `go mod init...`
2. `go get golang.ngrok.com/ngrok@v2.0.0`
  i. `go: golang.ngrok.com/ngrok@v2.0.0: invalid version: go.mod has post-v2 module path "golang.ngrok.com/ngrok/v2" at revision v2.0.0`
  ii. Makes sense, let's try again with the `/v2`
3. `go get golang.ngrok.com/ngrok/v2@v2.0.0`
4. main.go:

```go
package main

import (
	"context"
	"fmt"
	"log"
	"net/http"

	"golang.ngrok.com/ngrok/v2"
)

func main() {
	if err := run(context.Background()); err != nil {
		log.Fatal(err)
	}
}

func run(ctx context.Context) error {
	// ngrok.Listen uses ngrok.DefaultAgent which uses the NGROK_AUTHTOKEN
	// environment variable for auth
	ln, err := ngrok.Listen(ctx)
	if err != nil {
		return err
	}

	log.Println("Endpoint online", ln.URL())

	// Serve HTTP traffic on the ngrok endpoint
	return http.Serve(ln, http.HandlerFunc(handler))
}

func handler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintln(w, "Hello from ngrok-go!")
}

```


I'm not seeing the error with `go run ./main.go` or `go build`

**Comment by inconshreveable** [comment]
ty alice!

here's the line and file that your compiler is erroring on: https://github.com/ngrok/ngrok-go/blob/main/internal/tunnel/netx/logged_conn.go#L43

@kataras it sounds like maybe something is wrong with your local go package cache. might want to try clearing it and ensuring it fetches fresh source code

alternatively, from your example repro, you're pulling the v2 package (great!):

> Add dependency: go get golang.ngrok.com/ngrok@v2.0.0 (or any affected version)

but you're importing v1:

```
import (
    "context"
    "golang.ngrok.com/ngrok"
    ngrokconfig "golang.ngrok.com/ngrok/config"
)
```

**Comment by Alice-Lilith** [comment]
The logext.RandId should have been removed in https://github.com/ngrok/ngrok-go/pull/205

**Comment by kataras** [comment]
Strange guys because I see that error when deploying to azure as well (docker container, so it is not local) and I've already tried `go clean -modcache` using `go 1.25` in my own machine, still the same error.  

```sh
PS C:\github\iris-private> go clean -modcache
PS C:\github\iris-private> go build
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/andybalholm/brotli v1.2.0
go: downloading github.com/golang/snappy v1.0.0
go: downloading github.com/kataras/golog v0.1.13
go: downloading github.com/klauspost/compress v1.18.0
go: downloading golang.org/x/time v0.12.0
go: downloading github.com/iris-contrib/schema v0.0.7-0.20250208085038-f68827b0bbfa
go: downloading github.com/kataras/pg v1.0.11-0.20250805212606-fbefd3707823
go: downloading github.com/gomarkdown/markdown v0.0.0-20250810172220-2e2c11897d1a
go: downloading github.com/google/uuid v1.6.0
go: downloading github.com/mailru/easyjson v0.9.0
go: downloading github.com/microcosm-cc/bluemonday v1.0.27
go: downloading github.com/vmihailenco/msgpack/v5 v5.4.1
go: downloading google.golang.org/protobuf v1.36.7
go: downloading github.com/kataras/pio v0.0.14
go: downloading github.com/schollz/closestmatch v2.1.0+incompatible
go: downloading golang.ngrok.com/ngrok/v2 v2.0.0
go: downloading golang.org/x/crypto v0.41.0
go: downloading golang.org/x/net v0.43.0
go: downloading golang.org/x/sys v0.35.0
go: downloading golang.org/x/oauth2 v0.30.0
go: downloading github.com/blang/semver/v4 v4.0.0
go: downloading github.com/aymerick/douceur v0.2.0
go: downloading github.com/vmihailenco/tagparser/v2 v2.0.0
go: downloading github.com/jackc/pgx/v5 v5.7.5
go: downloading github.com/josharian/intern v1.0.0
go: downloading github.com/gertd/go-pluralize v0.2.1
go: downloading github.com/inconshreveable/log15/v3 v3.1.0
go: downloading go.uber.org/multierr v1.11.0
go: downloading golang.ngrok.com/muxado/v2 v2.0.1
go: downloading github.com/gorilla/css v1.0.1
go: downloading golang.org/x/text v0.28.0
go: downloading github.com/jpillora/backoff v1.0.0
go: downloading github.com/jackc/pgservicefile v0.0.0-20240606120523-5a60cdf6a761
go: downloading github.com/jackc/pgpassfile v1.0.0
go: downloading github.com/jackc/puddle/v2 v2.2.2
go: downloading github.com/mattn/go-colorable v0.1.14
go: downloading golang.org/x/term v0.34.0
go: downloading github.com/mattn/go-isatty v0.0.20
go: downloading golang.org/x/sync v0.16.0
# golang.ngrok.com/ngrok/v2/internal/tunnel/netx
C:\Users\kataras\go\pkg\mod\golang.ngrok.com\ngrok\v2@v2.0.0\internal\tunnel\netx\logged_conn.go:43:16: undefined: logext.RandId
```

**Comment by kataras** [comment]
Hi @Alice-Lilith and @Alice-Lilith, it's strange because I see that error when deploying to azure as well (docker container, so it is not local) and I've already tried `go clean -modcache` using `go 1.25` in my own machine, still the same error.  

```sh
PS C:\github\iris-private> go clean -modcache
PS C:\github\iris-private> go build
...
go: downloading golang.ngrok.com/ngrok/v2 v2.0.0
...
# golang.ngrok.com/ngrok/v2/internal/tunnel/netx
C:\Users\kataras\go\pkg\mod\golang.ngrok.com\ngrok\v2@v2.0.0\internal\tunnel\netx\logged_conn.go:43:16: undefined: logext.RandId
```

And if you see, the [function call](https://github.com/ngrok/ngrok-go/blob/v2.0.0/internal/tunnel/netx/logged_conn.go#L43) and the import dependency exists at `v2.0.0`'s commits: 

https://github.com/ngrok/ngrok-go/blob/6bc8021c53f29f42c9b05c54aa7ea7e6810d906b/internal/tunnel/netx/logged_conn.go#L43

Not in `main` but in the `v2.0.0` version. I don't know why you build with success, maybe a different go proxy(?). **You need to publish a new release v2.0.1** to sync with main and it will be fixed:

```sh
PS C:\github\iris-private> go get golang.ngrok.com/ngrok/v2@main; go mod tidy          
go: downloading golang.ngrok.com/ngrok/v2 v2.0.1-0.20250807203556-68351cc649fd
go: upgraded golang.ngrok.com/ngrok/v2 v2.0.0 => v2.0.1-0.20250807203556-68351cc649fd
...
PS C:\github\iris-private> go build
PS C:\github\iris-private> 
```

> Success with go get golang.ngrok.com/ngrok/v2@main but not with go get golang.ngrok.com/ngrok/v2@latest.

**Comment by kataras** [comment]
Hi @inconshreveable and @Alice-Lilith, it's strange because I see that error when deploying to azure as well (docker container, so it is not local) and I've already tried `go clean -modcache` using `go 1.25` in my own machine, still the same error.  

```sh
PS C:\github\iris-private> go clean -modcache
PS C:\github\iris-private> go build
...
go: downloading golang.ngrok.com/ngrok/v2 v2.0.0
...
# golang.ngrok.com/ngrok/v2/internal/tunnel/netx
C:\Users\kataras\go\pkg\mod\golang.ngrok.com\ngrok\v2@v2.0.0\internal\tunnel\netx\logged_conn.go:43:16: undefined: logext.RandId
```

And if you see, the [function call](https://github.com/ngrok/ngrok-go/blob/v2.0.0/internal/tunnel/netx/logged_conn.go#L43) and the import dependency exists at `v2.0.0`'s commits: 

https://github.com/ngrok/ngrok-go/blob/6bc8021c53f29f42c9b05c54aa7ea7e6810d906b/internal/tunnel/netx/logged_conn.go#L43

Not in `main` but in the `v2.0.0` version. I don't know why you build with success with the `v2.0.0` tagged version. **You need to publish a new release v2.0.1** to sync with main and it will be fixed:

```sh
PS C:\github\iris-private> go get golang.ngrok.com/ngrok/v2@main; go mod tidy          
go: downloading golang.ngrok.com/ngrok/v2 v2.0.1-0.20250807203556-68351cc649fd
go: upgraded golang.ngrok.com/ngrok/v2 v2.0.0 => v2.0.1-0.20250807203556-68351cc649fd
...
PS C:\github\iris-private> go build
PS C:\github\iris-private> 
```

> Success with go get golang.ngrok.com/ngrok/v2@main but not with go get golang.ngrok.com/ngrok/v2@latest.
